language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - build-tools-27.0.3    
    # - platform-tools
    # The SDK version used to compile your project
    - android-27
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    # Additional components


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-26
    # - sys-img-armeabi-v7a-android-17
licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
